/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Ricardo_pc
 */
public class Frm_Venda extends javax.swing.JDialog {

    float preco_produto;
    float total = 0;

    //  int i = 0;
    /**
     * Creates new form Frm_Venda
     */
    public Frm_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Mascara para escrever a data no formato Brasileiro.
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jFormattedTextField_DATA_VENDA.setFormatterFactory(new DefaultFormatterFactory(form));

        } catch (ParseException ex) {
            Logger.getLogger(Frm_Venda.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Pegar data do sistema.
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        jFormattedTextField_DATA_VENDA.setText(df.format(hoje));

        //Alterar cor da linha ao ser selecionado.
        jTab_Itens_Venda.setSelectionBackground(Color.red);
        jT_tabela_Pesq_Prod.setSelectionBackground(Color.blue);
        jT_tabela_pesq_Client.setSelectionBackground(Color.green);
        
        
        
        //Limpa o item da tabela que o mouse selecionou.
       // ((DefaultTableModel) jTab_Itens_Venda.getModel()).removeRow(jTab_Itens_Venda.getSelectedRow());


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jT_nome_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField_DATA_VENDA = new javax.swing.JFormattedTextField();
        jT_Busca_cliente = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jT_Nome_Produto = new javax.swing.JTextField();
        jT_Busca_Produto = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jT_Quantidade_Produto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_Valor_Iten = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jT_Valor_total_venda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tabela_pesq_Client = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_tabela_Pesq_Prod = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        JB_Final_Venda = new javax.swing.JButton();
        jB_Adicionar_iten_venda = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTab_Itens_Venda = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JT_Código_CLiente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JT_Cod_Produto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de vendas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Vendas");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome do cliente:");

        jLabel3.setText("Data Venda:");

        jFormattedTextField_DATA_VENDA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jFormattedTextField_DATA_VENDA.setEnabled(false);
        jFormattedTextField_DATA_VENDA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_DATA_VENDAFocusGained(evt);
            }
        });
        jFormattedTextField_DATA_VENDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_DATA_VENDAActionPerformed(evt);
            }
        });

        jT_Busca_cliente.setText("Buscar");
        jT_Busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Busca_clienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Produto:");

        jT_Nome_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Nome_ProdutoActionPerformed(evt);
            }
        });

        jT_Busca_Produto.setText("Buscar");
        jT_Busca_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Busca_ProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Quantidade:");

        jT_Quantidade_Produto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_Quantidade_ProdutoFocusGained(evt);
            }
        });

        jLabel6.setText("Valor por iten:");

        jLabel7.setText("Valor Total:");

        jT_Valor_total_venda.setBackground(new java.awt.Color(0, 0, 0));
        jT_Valor_total_venda.setForeground(new java.awt.Color(255, 255, 255));
        jT_Valor_total_venda.setCaretColor(new java.awt.Color(255, 255, 255));

        jT_tabela_pesq_Client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ));
        jT_tabela_pesq_Client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_tabela_pesq_ClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_tabela_pesq_Client);
        if (jT_tabela_pesq_Client.getColumnModel().getColumnCount() > 0) {
            jT_tabela_pesq_Client.getColumnModel().getColumn(0).setMinWidth(60);
            jT_tabela_pesq_Client.getColumnModel().getColumn(0).setPreferredWidth(60);
            jT_tabela_pesq_Client.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jLabel8.setText("Tabela de Pesquisa Cliente:");

        jT_tabela_Pesq_Prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Vencimento", "Lote"
            }
        ));
        jT_tabela_Pesq_Prod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_tabela_Pesq_ProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_tabela_Pesq_Prod);
        if (jT_tabela_Pesq_Prod.getColumnModel().getColumnCount() > 0) {
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(0).setMinWidth(50);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(0).setPreferredWidth(50);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(0).setMaxWidth(50);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(2).setMinWidth(80);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(2).setPreferredWidth(80);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(2).setMaxWidth(80);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(3).setMinWidth(90);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(3).setPreferredWidth(90);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(3).setMaxWidth(90);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(4).setMinWidth(60);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(4).setPreferredWidth(60);
            jT_tabela_Pesq_Prod.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jLabel9.setText("Tabela Pesquisa Produto:");

        JB_Final_Venda.setText("Finalizar Venda");
        JB_Final_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Final_VendaActionPerformed(evt);
            }
        });

        jB_Adicionar_iten_venda.setText("ADD");
        jB_Adicionar_iten_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Adicionar_iten_vendaActionPerformed(evt);
            }
        });

        jTab_Itens_Venda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Data", "Valor Uni"
            }
        ));
        jScrollPane3.setViewportView(jTab_Itens_Venda);
        if (jTab_Itens_Venda.getColumnModel().getColumnCount() > 0) {
            jTab_Itens_Venda.getColumnModel().getColumn(1).setMinWidth(70);
            jTab_Itens_Venda.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTab_Itens_Venda.getColumnModel().getColumn(1).setMaxWidth(70);
            jTab_Itens_Venda.getColumnModel().getColumn(2).setMinWidth(90);
            jTab_Itens_Venda.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTab_Itens_Venda.getColumnModel().getColumn(2).setMaxWidth(90);
            jTab_Itens_Venda.getColumnModel().getColumn(3).setMinWidth(70);
            jTab_Itens_Venda.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTab_Itens_Venda.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        jLabel10.setText("Itens de Venda:");

        jLabel11.setText("Código Cliente:");

        JT_Código_CLiente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        JT_Código_CLiente.setEnabled(false);
        JT_Código_CLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_Código_CLienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Codigo Produto:");

        JT_Cod_Produto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        JT_Cod_Produto.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(JB_Final_Venda)
                            .addGap(197, 197, 197)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jT_Valor_total_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jT_Quantidade_Produto))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JT_Código_CLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jT_Valor_Iten, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jB_Adicionar_iten_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jT_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_Busca_cliente)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jT_Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_Busca_Produto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextField_DATA_VENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JT_Cod_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Busca_cliente)
                    .addComponent(jT_Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_Busca_Produto))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JT_Código_CLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(JT_Cod_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jT_Quantidade_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_Valor_Iten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB_Adicionar_iten_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextField_DATA_VENDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jT_Valor_total_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(JB_Final_Venda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(354, 354, 354))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField_DATA_VENDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_DATA_VENDAActionPerformed


    }//GEN-LAST:event_jFormattedTextField_DATA_VENDAActionPerformed

    private void jT_Busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Busca_clienteActionPerformed

        Connection conn = null;

        try {
            conn = Conexao_Dao.getConnection();

            if (jT_nome_cliente.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Campo em branco não pode ser pesquizado!");
            } else {

                String query = "select id_cliente, nome_cliente from cliente where nome_cliente like ? ";

                PreparedStatement pst;
                pst = (PreparedStatement) conn.prepareStatement(query);

                pst.setString(1, '%' + jT_nome_cliente.getText() + '%');

                ResultSet rs;
                rs = pst.executeQuery();

                DefaultTableModel model = (DefaultTableModel) jT_tabela_pesq_Client.getModel();

                model.setNumRows(0);

                // Enquanto huver proximo ele vai executar para pegar todos resultados e mostrar na tabela
                while (rs.next()) {

                    model.addRow(
                            new Object[]{
                                rs.getString("id_cliente"),
                                rs.getString("nome_cliente"),}
                    );

                }
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de SQL\nEROO:" + ex);
        }


    }//GEN-LAST:event_jT_Busca_clienteActionPerformed

    private void jT_Busca_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Busca_ProdutoActionPerformed

        String produto = String.valueOf(jT_Nome_Produto.getText());
        try {

            Connection conn = null;
            conn = Conexao_Dao.getConnection();
            if (produto.equals("")) {

                JOptionPane.showMessageDialog(rootPane, "Campo em branco não pode ser pesquisado!");

            } else {

                String query = "SELECT id_produto,nome_produto,quantidade_produto,"
                        + "data_vencimento,lote FROM estoque WHERE nome_produto LIKE ?";

                PreparedStatement pst;
                pst = (PreparedStatement) conn.prepareStatement(query);

                pst.setString(1, '%' + jT_Nome_Produto.getText() + '%');

                ResultSet rs;
                rs = pst.executeQuery();

                DefaultTableModel model = (DefaultTableModel) jT_tabela_Pesq_Prod.getModel();

                model.setNumRows(0);

                // Enquanto houver proximo ele vai executar para pegar todos resultados e mostrar na tabela
                while (rs.next()) {

                    model.addRow(
                            new Object[]{
                                rs.getString("id_produto"),
                                rs.getString("nome_produto"),
                                rs.getString("quantidade_produto"),
                                rs.getString("data_vencimento"),
                                rs.getString("lote")
                            }
                    );

                }

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro de SQL\nEROO:" + ex);
        }


    }//GEN-LAST:event_jT_Busca_ProdutoActionPerformed

    private void jT_tabela_pesq_ClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_tabela_pesq_ClientMouseClicked

        //Seta no campo de testo nome do cliente quando clica duas vezes com o mouse
        //Obserbação especial para o numero 1 no final da linha, é como um vetor indica a posição "2" da coluna que é o nome.
        String codigo = "" + jT_tabela_pesq_Client.getValueAt(jT_tabela_pesq_Client.getSelectedRow(), 0);
        JT_Código_CLiente.setText(codigo);
        String nome_cliente = "" + jT_tabela_pesq_Client.getValueAt(jT_tabela_pesq_Client.getSelectedRow(), 1);
        jT_nome_cliente.setText(nome_cliente);

    }//GEN-LAST:event_jT_tabela_pesq_ClientMouseClicked

    private void jT_tabela_Pesq_ProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_tabela_Pesq_ProdMouseClicked

        try {
            //Seta o valor no campo quando é clicado na tabela(Neste caso expecifico o valor do nome do produto).
            String nome_Produto = "" + jT_tabela_Pesq_Prod.getValueAt(jT_tabela_Pesq_Prod.getSelectedRow(), 1);
            jT_Nome_Produto.setText(nome_Produto);
            
             String cod_prod = "" + jT_tabela_Pesq_Prod.getValueAt(jT_tabela_Pesq_Prod.getSelectedRow(),0);
             JT_Cod_Produto.setText(cod_prod);
             
             
            Connection conn;

            conn = Conexao_Dao.getConnection();
            //Faz a busca no banco 
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from estoque where nome_produto ='" + nome_Produto + "'");
            //Guarda o valor dentro da variavel preco_produto.
            rs.first();
            preco_produto = rs.getFloat("valor_unitario");
            //Mostra(seta) no campo valor itens.
            jT_Valor_Iten.setText(String.valueOf(preco_produto));
            jT_Quantidade_Produto.setText("1");
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar preço\nERRO:" + ex);
        }


    }//GEN-LAST:event_jT_tabela_Pesq_ProdMouseClicked

    private void jT_Quantidade_ProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_Quantidade_ProdutoFocusGained

        //Efetuando a multiplicação para preencher o campo de valor total
        float valorTotal;
        valorTotal = Float.parseFloat(jT_Valor_Iten.getText()) * Integer.parseInt(jT_Quantidade_Produto.getText());
        jT_Valor_total_venda.setText(String.valueOf(valorTotal));


    }//GEN-LAST:event_jT_Quantidade_ProdutoFocusGained

    private void jFormattedTextField_DATA_VENDAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_DATA_VENDAFocusGained
        //Efetuando a multiplicação para preencher o campo de valor total, quando preencher a data.
        float valorTotal;
        valorTotal = Float.parseFloat(jT_Valor_Iten.getText()) * Integer.parseInt(jT_Quantidade_Produto.getText());
        jT_Valor_total_venda.setText(String.valueOf(total));
    }//GEN-LAST:event_jFormattedTextField_DATA_VENDAFocusGained

    private void jB_Adicionar_iten_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Adicionar_iten_vendaActionPerformed

     
        
         Connection conn = null;
        try {
            conn = Conexao_Dao.getConnection();
            
             Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM estoque WHERE nome_produto ='"
                    + jT_Nome_Produto.getText() + "'");
            
            rs.first();
            int quantidade;
            quantidade = rs.getInt("quantidade_produto");
            
            if(quantidade >= Integer.parseInt(jT_Quantidade_Produto.getText())){ 
                //Query para atualizar banco de dados
                String query = "UPDATE estoque set quantidade_produto ="
                        + "quantidade_produto - " + (jT_Quantidade_Produto.getText()) + ",data_saida=? WHERE nome_produto = ?";
               
                PreparedStatement ps;
                ps = (PreparedStatement) conn.prepareStatement(query);
                
                 //Converte data para banco ex: pega 13/05/1983 e manda pro banco em:1983/05/13.
                String dia = jFormattedTextField_DATA_VENDA.getText().substring(0, 2);
                String mes = jFormattedTextField_DATA_VENDA.getText().substring(3, 5);
                String ano = jFormattedTextField_DATA_VENDA.getText().substring(6);
                String dataParaMysql = ano+"-"+mes+"-"+dia;
                ps.setString(1, dataParaMysql);
                ps.setString(2, jT_Nome_Produto.getText());
                
                ps.executeUpdate();
        
        //Adiciona na tabela os campos que estão preenchidos com os valores de nome, quant, data, valor.
        DefaultTableModel model = (DefaultTableModel) jTab_Itens_Venda.getModel();
            model.addRow (new Object [] {jT_Nome_Produto.getText(),jT_Quantidade_Produto.getText(),jFormattedTextField_DATA_VENDA.getText(),jT_Valor_Iten.getText()});
        
          //Atualiza o valor total da venda com todos os itens comprados.
          total = total + ((Float.parseFloat(jT_Valor_Iten.getText())) * (Integer.parseInt(jT_Quantidade_Produto.getText())));
          jT_Valor_total_venda.setText(String.valueOf(total));
          
         //Atualizar nova tabela(Vendidos) onde ira conter todas as informações de quem Comprou(Nome) e oque comprou.
          String quer = "insert into Vendidos (codigoCliente, nomeCliente, nomeProduto, Quantidade, ValorIten, dataVenda)"
                  + "VALUES (?,?,?,?,?,?)";
          
          PreparedStatement pst = conn.prepareStatement(quer);
          
          pst.setString(1, JT_Código_CLiente.getText());
          pst.setString(2,jT_nome_cliente.getText());
          pst.setString(3, jT_Nome_Produto.getText());
          pst.setString(4, jT_Quantidade_Produto.getText());
          pst.setString(5, jT_Valor_Iten.getText());
         
          //Converte data para banco ex: pega 13/05/1983 e manda pro banco em:1983/05/13.
                String di = jFormattedTextField_DATA_VENDA.getText().substring(0, 2);
                String me = jFormattedTextField_DATA_VENDA.getText().substring(3, 5);
                String an = jFormattedTextField_DATA_VENDA.getText().substring(6);
                String dataMysql = an+"-"+me+"-"+di;
                pst.setString(6, dataMysql);
         
          pst.execute();
          
           conn.close();
          
        conn.close();
            }else{
                       
            JOptionPane.showMessageDialog(rootPane,"Não possui essa quantidade  em estoque!" );
            }
          } catch (SQLException ex) {
            Logger.getLogger(Frm_Venda.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jB_Adicionar_iten_vendaActionPerformed

    private void JB_Final_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Final_VendaActionPerformed

//        for (int j = 0; j < i ; j++)
//        {
//            
//        }
//        jTab_Itens_Venda.getModel().removeTableModelListener(jTab_Itens_Venda); ;
        //Limpar tabela itens venda.
        ((DefaultTableModel) jTab_Itens_Venda.getModel()).setRowCount(0);
           //Limpa Tabela inteira.
            ((DefaultTableModel) jT_tabela_Pesq_Prod.getModel()).setRowCount(0);
               //Limpa Tabela inteira.
            ((DefaultTableModel) jT_tabela_pesq_Client.getModel()).setRowCount(0);

//        Connection conn = null;
//        try {
//            conn = Conexao_Dao.getConnection();
//
//            Statement st = conn.createStatement();
//            ResultSet rs = st.executeQuery("SELECT * FROM estoque WHERE nome_produto ='"
//                    + jT_Nome_Produto.getText() + "'");
//
//            rs.first();
//            int quantidade;
//            quantidade = rs.getInt("quantidade_produto");
//
//            if (quantidade >= Integer.parseInt(jT_Quantidade_Produto.getText())) {
//                //Query para atualizar banco de dados
//                String query = "UPDATE estoque set quantidade_produto ="
//                        + "quantidade_produto - " + (jT_Quantidade_Produto.getText()) + ",data_saida=? WHERE nome_produto = ?";
//
//                PreparedStatement ps;
//                ps = (PreparedStatement) conn.prepareStatement(query);
//
//                //Converte data para banco ex: pega 13/05/1983 e manda pro banco em:1983/05/13.
//                String dia = jFormattedTextField_DATA_VENDA.getText().substring(0, 2);
//                String mes = jFormattedTextField_DATA_VENDA.getText().substring(3, 5);
//                String ano = jFormattedTextField_DATA_VENDA.getText().substring(6);
//                String dataParaMysql = ano + "-" + mes + "-" + dia;
//                ps.setString(1, dataParaMysql);
//                ps.setString(2, jT_Nome_Produto.getText());
//
//                ps.executeUpdate();
//
//                //Adiciona na tabela os campos que estão preenchidos com os valores de nome, quant, data, valor.
//                //   DefaultTableModel model = (DefaultTableModel) jTab_Itens_Venda.getModel();
//                //    model.addRow (new Object [] {jT_Nome_Produto.getText(),jT_Quantidade_Produto.getText(),jFormattedTextField_DATA_VENDA.getText(),jT_Valor_Iten.getText()});
//                //Atualizar nova tabela(Vendidos) onde ira conter todas as informações de quem Comprou(Nome) e oque comprou.
//                String quer = "insert into Vendidos (codigoCliente, nomeCliente, nomeProduto, Quantidade, ValorIten, dataVenda)"
//                        + "VALUES (?,?,?,?,?,?)";
//
//                PreparedStatement pst = conn.prepareStatement(quer);
//
//                pst.setString(1, JT_Código_CLiente.getText());
//                pst.setString(2, jT_nome_cliente.getText());
//                pst.setString(3, jT_Nome_Produto.getText());
//                pst.setString(4, jT_Quantidade_Produto.getText());
//                pst.setString(5, jT_Valor_Iten.getText());
//
//                //Converte data para banco ex: pega 13/05/1983 e manda pro banco em:1983/05/13.
//                String di = jFormattedTextField_DATA_VENDA.getText().substring(0, 2);
//                String me = jFormattedTextField_DATA_VENDA.getText().substring(3, 5);
//                String an = jFormattedTextField_DATA_VENDA.getText().substring(6);
//                String dataMysql = an + "-" + me + "-" + di;
//                pst.setString(6, dataMysql);
//
//                pst.execute();
//
//                conn.close();
//
//                conn.close();
//            } else {
//
//                JOptionPane.showMessageDialog(rootPane, "Não possui essa quantidade  em estoque!");
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Frm_Venda.class.getName()).log(Level.SEVERE, null, ex);
//        }

        JT_Código_CLiente.setText("");
        jT_nome_cliente.setText("");
        jT_Nome_Produto.setText("");
        jT_Quantidade_Produto.setText("");
        jT_Valor_Iten.setText("");
        jFormattedTextField_DATA_VENDA.setText("");
        jT_Valor_total_venda.setText("");
        JT_Cod_Produto.setText("");
        JOptionPane.showMessageDialog(rootPane, "Venda Concluida!");
    }//GEN-LAST:event_JB_Final_VendaActionPerformed

    private void JT_Código_CLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_Código_CLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_Código_CLienteActionPerformed

    private void jT_Nome_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Nome_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Nome_ProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Venda dialog = new Frm_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Final_Venda;
    private javax.swing.JTextField JT_Cod_Produto;
    private javax.swing.JTextField JT_Código_CLiente;
    private javax.swing.JButton jB_Adicionar_iten_venda;
    private javax.swing.JFormattedTextField jFormattedTextField_DATA_VENDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jT_Busca_Produto;
    private javax.swing.JToggleButton jT_Busca_cliente;
    private javax.swing.JTextField jT_Nome_Produto;
    private javax.swing.JTextField jT_Quantidade_Produto;
    private javax.swing.JTextField jT_Valor_Iten;
    private javax.swing.JTextField jT_Valor_total_venda;
    private javax.swing.JTextField jT_nome_cliente;
    private javax.swing.JTable jT_tabela_Pesq_Prod;
    private javax.swing.JTable jT_tabela_pesq_Client;
    private javax.swing.JTable jTab_Itens_Venda;
    // End of variables declaration//GEN-END:variables
}
