package View;

//import Relatório.ExecutaRelatorio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class J_Principal extends javax.swing.JFrame {

    //Declarando variavel de auxilio
    private int aux;

    /**
     * Creates new form J_Principal
     */
    public J_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Pesquisa_Inteligente_tabela = new javax.swing.JTable();
        jB_Pesquisa_Inteligente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadio_15dias = new javax.swing.JRadioButton();
        jRadio_7dias = new javax.swing.JRadioButton();
        jRadio_30dias = new javax.swing.JRadioButton();
        jRadio_60dias = new javax.swing.JRadioButton();
        jCheck_Box_pesq_Intel = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        JB_Rel_Venda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_BI_Painel_Alerta = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Jcadastrar_produto = new javax.swing.JMenuItem();
        jMe_cadastrar_cliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jconsulta_produto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jvenda_produto = new javax.swing.JMenuItem();
        j_venda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jM_Itens_preocupantes = new javax.swing.JMenuItem();
        J_Grafico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle_Estoque");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisa Inteligente");

        jT_Pesquisa_Inteligente_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Produto", "Quantidade", "Data Vencimento"
            }
        ));
        jScrollPane1.setViewportView(jT_Pesquisa_Inteligente_tabela);
        if (jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumnCount() > 0) {
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(1).setMinWidth(90);
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(1).setPreferredWidth(90);
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(1).setMaxWidth(90);
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(2).setMinWidth(120);
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(2).setPreferredWidth(120);
            jT_Pesquisa_Inteligente_tabela.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        jB_Pesquisa_Inteligente.setText("Pesquisar");
        jB_Pesquisa_Inteligente.setEnabled(false);
        jB_Pesquisa_Inteligente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Pesquisa_InteligenteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        buttonGroup1.add(jRadio_15dias);
        jRadio_15dias.setText("15 dias");
        jRadio_15dias.setEnabled(false);
        jRadio_15dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_15diasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_7dias);
        jRadio_7dias.setText("7 dias");
        jRadio_7dias.setEnabled(false);
        jRadio_7dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_7diasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_30dias);
        jRadio_30dias.setText("30 dias");
        jRadio_30dias.setEnabled(false);
        jRadio_30dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_30diasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_60dias);
        jRadio_60dias.setText("60 dias");
        jRadio_60dias.setEnabled(false);
        jRadio_60dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_60diasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jRadio_7dias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadio_15dias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jRadio_30dias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jRadio_60dias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_7dias)
                    .addComponent(jRadio_60dias)
                    .addComponent(jRadio_30dias)
                    .addComponent(jRadio_15dias))
                .addContainerGap())
        );

        jCheck_Box_pesq_Intel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheck_Box_pesq_IntelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Relatório");

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        JB_Rel_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Venda.png"))); // NOI18N
        JB_Rel_Venda.setText("RelatórioVenda");
        JB_Rel_Venda.setToolTipText("Vendas");
        JB_Rel_Venda.setEnabled(false);
        JB_Rel_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_Rel_VendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JB_Rel_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_Rel_Venda)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheck_Box_pesq_Intel)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_Pesquisa_Inteligente)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCheck_Box_pesq_Intel))
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Pesquisa_Inteligente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jT_BI_Painel_Alerta.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jT_BI_Painel_Alerta.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        jT_BI_Painel_Alerta.setEnabled(false);
        jScrollPane2.setViewportView(jT_BI_Painel_Alerta);

        jMenu1.setText("Cadastrar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Jcadastrar_produto.setText("Produto");
        Jcadastrar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcadastrar_produtoActionPerformed(evt);
            }
        });
        jMenu1.add(Jcadastrar_produto);

        jMe_cadastrar_cliente.setText("Cliente");
        jMe_cadastrar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMe_cadastrar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMe_cadastrar_cliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        jconsulta_produto.setText("consulta_produto");
        jconsulta_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconsulta_produtoActionPerformed(evt);
            }
        });
        jMenu2.add(jconsulta_produto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Vender");

        jvenda_produto.setText("Venda_produto");
        jvenda_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvenda_produtoActionPerformed(evt);
            }
        });
        jMenu3.add(jvenda_produto);

        j_venda.setText("Venda");
        j_venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_vendaActionPerformed(evt);
            }
        });
        jMenu3.add(j_venda);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("BI");

        jM_Itens_preocupantes.setText("Itens_preocupantes");
        jM_Itens_preocupantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Itens_preocupantesActionPerformed(evt);
            }
        });
        jMenu4.add(jM_Itens_preocupantes);

        J_Grafico.setText("Grafico");
        J_Grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J_GraficoActionPerformed(evt);
            }
        });
        jMenu4.add(J_Grafico);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed


    }//GEN-LAST:event_jMenu1ActionPerformed

    private void Jcadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcadastrar_produtoActionPerformed
        J_CadProduto jc = new J_CadProduto(null, true);
        jc.setVisible(true);
    }//GEN-LAST:event_Jcadastrar_produtoActionPerformed

    private void jconsulta_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconsulta_produtoActionPerformed
        J_ConsultaProduto jco = new J_ConsultaProduto(null, true);
        jco.setVisible(true);

    }//GEN-LAST:event_jconsulta_produtoActionPerformed

    private void jvenda_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvenda_produtoActionPerformed

        J_Venda jv = new J_Venda(null, true);
        jv.setVisible(true);

    }//GEN-LAST:event_jvenda_produtoActionPerformed

    private void j_vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_vendaActionPerformed

        Frm_Venda frm = new Frm_Venda(null, true);
        frm.setVisible(true);

    }//GEN-LAST:event_j_vendaActionPerformed

    private void jM_Itens_preocupantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Itens_preocupantesActionPerformed

        //Tornando visivel os paineis.
        J_BI jb = new J_BI(null, true);
        jb.setVisible(true);
    }//GEN-LAST:event_jM_Itens_preocupantesActionPerformed

    private void jB_Pesquisa_InteligenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Pesquisa_InteligenteActionPerformed

        //Condição para executar a opção desejada.
        if (aux == 1) {

            Connection conexao = null;
            try {
                conexao = Conexao_Dao.getConnection();
                String query = "Select id_produto,nome_produto,data_vencimento,quantidade_produto from estoque "
                        + "where DATEDIFF (data_vencimento ,NOW()) < ?";

                PreparedStatement pst;
                pst = (PreparedStatement) conexao.prepareStatement(query);
                pst.setString(1, jRadio_7dias.getText());
                ResultSet rst;
                rst = pst.executeQuery();
                DefaultTableModel model = (DefaultTableModel) jT_Pesquisa_Inteligente_tabela.getModel();
                model.setNumRows(0);
                while (rst.next()) {
                    model.addRow(
                            new Object[]{
                                rst.getString("nome_produto"),
                                rst.getString("quantidade_produto"),
                                rst.getString("data_vencimento")
                            }
                    );
                }
                
                
                String Alert ="¨¨¨¨¨¨¨¨¨¨¨¨¨¨¨ATENÇÃO MAXIMA:¨¨¨¨¨¨¨¨¨¨¨¨\n\n Produtos altamente em risco, entre em contato com o fornecedor para solicitar auxilio de queima de estoque, o sistema recomenda que você faça mega promoção.\n\n ***compre 1 e ganhe mais 1**** ";
                jT_BI_Painel_Alerta.setText(Alert);

            } catch (SQLException ex) {
                Logger.getLogger(J_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (aux == 2) {

            Connection conexao = null;
            try {
                conexao = Conexao_Dao.getConnection();
                String query = "Select id_produto,nome_produto,data_vencimento,quantidade_produto from estoque "
                        + "where DATEDIFF (data_vencimento ,NOW()) <= ?";

                PreparedStatement pst;
                pst = (PreparedStatement) conexao.prepareStatement(query);
                pst.setString(1, jRadio_15dias.getText());
                ResultSet rst;
                rst = pst.executeQuery();
                DefaultTableModel model = (DefaultTableModel) jT_Pesquisa_Inteligente_tabela.getModel();
                model.setNumRows(0);
                while (rst.next()) {
                    model.addRow(
                            new Object[]{
                                rst.getString("nome_produto"),
                                rst.getString("quantidade_produto"),
                                rst.getString("data_vencimento")
                            }
                    );
                }
                
                String Alert ="ALERTA: \n O sistema identificou produtos que estão próximo de seu vencimento e recomenda que comece a tomar atitudes.\n\n ******PROMOCÕES****** \n  ºCombos\n  ºRebaixe de preço\n  ºCompre 2 e ganhe mais 1";
                jT_BI_Painel_Alerta.setText(Alert);
            } catch (SQLException ex) {
                Logger.getLogger(J_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (aux == 3) {

            Connection conexao = null;
            try {
                conexao = Conexao_Dao.getConnection();
                String query = "Select id_produto,nome_produto,data_vencimento,quantidade_produto from estoque "
                        + "where DATEDIFF (data_vencimento ,NOW()) <= ?";

                PreparedStatement pst;
                pst = (PreparedStatement) conexao.prepareStatement(query);
                pst.setString(1, jRadio_30dias.getText());
                ResultSet rst;
                rst = pst.executeQuery();
                DefaultTableModel model = (DefaultTableModel) jT_Pesquisa_Inteligente_tabela.getModel();
                model.setNumRows(0);
                while (rst.next()) {
                    model.addRow(
                            new Object[]{
                                rst.getString("nome_produto"),
                                rst.getString("quantidade_produto"),
                                rst.getString("data_vencimento")
                            }
                    );
                }
                
                String Alert = "ALERTA: \n O sistema identificou produtos que precisam de atenção e recomenda que melhore a visibilidade desses produtos! ";
                jT_BI_Painel_Alerta.setText(Alert);

            } catch (SQLException ex) {
                Logger.getLogger(J_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (aux == 4) {

            Connection conexao = null;
            try {
                conexao = Conexao_Dao.getConnection();
                String query = "Select id_produto,nome_produto,data_vencimento,quantidade_produto from estoque "
                        + "where DATEDIFF (data_vencimento ,NOW()) <= ?";

                PreparedStatement pst;
                pst = (PreparedStatement) conexao.prepareStatement(query);
                pst.setString(1, jRadio_60dias.getText());
                ResultSet rst;
                rst = pst.executeQuery();
                DefaultTableModel model = (DefaultTableModel) jT_Pesquisa_Inteligente_tabela.getModel();
                model.setNumRows(0);
                while (rst.next()) {
                    model.addRow(
                            new Object[]{
                                rst.getString("nome_produto"),
                                rst.getString("quantidade_produto"),
                                rst.getString("data_vencimento")
                            }
                    );
                }
                
                String Alert = "Produtos sem grandes riscos, porem necessita de atenção e controle, o sistema recomenda que melhore a visibilidade dos produtos! ";
                jT_BI_Painel_Alerta.setText(Alert);

            } catch (SQLException ex) {
                Logger.getLogger(J_Principal.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            JOptionPane.showMessageDialog(this, "Selecione uma opção de dias\nERROR");

        }


    }//GEN-LAST:event_jB_Pesquisa_InteligenteActionPerformed

    private void jRadio_7diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_7diasActionPerformed
        //Inserindo valores na variavel.
        aux = (1);
    }//GEN-LAST:event_jRadio_7diasActionPerformed

    private void jRadio_15diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_15diasActionPerformed

        aux = (2);
    }//GEN-LAST:event_jRadio_15diasActionPerformed

    private void jRadio_30diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_30diasActionPerformed

        aux = (3);
    }//GEN-LAST:event_jRadio_30diasActionPerformed

    private void jRadio_60diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_60diasActionPerformed

        aux = (4);
    }//GEN-LAST:event_jRadio_60diasActionPerformed

    private void J_GraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J_GraficoActionPerformed

        Grafico_jFreeChart gra = new Grafico_jFreeChart(null, true);
        gra.setVisible(true);
    }//GEN-LAST:event_J_GraficoActionPerformed

    private void jCheck_Box_pesq_IntelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheck_Box_pesq_IntelActionPerformed

        if (jCheck_Box_pesq_Intel.isSelected()) {
            //Torna os Campos e Campos visiveis após CheckBox ser selecionado.
            jB_Pesquisa_Inteligente.setEnabled(true);
            jRadio_7dias.setEnabled(true);
            jRadio_15dias.setEnabled(true);
            jRadio_30dias.setEnabled(true);
            jRadio_60dias.setEnabled(true);
           // JB_Cod_BArra.setEnabled(true);
           // JB_Graficos.setEnabled(true);
          //  JB_Relat_Estoque.setEnabled(true);
            JB_Rel_Venda.setEnabled(true);
        } else {

            jCheck_Box_pesq_Intel.setSelected(false);
            jB_Pesquisa_Inteligente.setEnabled(false);
            jRadio_7dias.setEnabled(false);
            jRadio_15dias.setEnabled(false);
            jRadio_30dias.setEnabled(false);
            jRadio_60dias.setEnabled(false);
            //JB_Cod_BArra.setEnabled(false);
           // JB_Graficos.setEnabled(false);
           // JB_Relat_Estoque.setEnabled(false);
            JB_Rel_Venda.setEnabled(false);

            //Limpa Tabela inteira.
            ((DefaultTableModel) jT_Pesquisa_Inteligente_tabela.getModel()).setRowCount(0);
            
            jT_BI_Painel_Alerta.setText("");
        }
    }//GEN-LAST:event_jCheck_Box_pesq_IntelActionPerformed

    private void jMe_cadastrar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMe_cadastrar_clienteActionPerformed

        FRM_Cliente frm = new FRM_Cliente(this, true);
        frm.setVisible(true);
    }//GEN-LAST:event_jMe_cadastrar_clienteActionPerformed

    private void JB_Rel_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_Rel_VendaActionPerformed

      try {
            Connection conn = null;
            conn = Conexao_Dao.getConnection();
            Statement st = conn.createStatement();

            try {
                 Map parametros = new HashMap();
              
                JasperPrint print = JasperFillManager.fillReport("C:/Users/Ricardo_pc/Desktop/TCC_A/src/Relatório/Teste.jasper", parametros, conn);
               
               // JasperViewer.viewReport(print);
                 
            JasperViewer view = new JasperViewer(print, false);
            view.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
            view.setDefaultCloseOperation(JasperViewer.DISPOSE_ON_CLOSE);
            view.setVisible(true);
               

               
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro printErro:\n" + ex);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro:\n" + e);
        }
    }//GEN-LAST:event_JB_Rel_VendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_Rel_Venda;
    private javax.swing.JMenuItem J_Grafico;
    private javax.swing.JMenuItem Jcadastrar_produto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jB_Pesquisa_Inteligente;
    private javax.swing.JCheckBox jCheck_Box_pesq_Intel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jM_Itens_preocupantes;
    private javax.swing.JMenuItem jMe_cadastrar_cliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadio_15dias;
    private javax.swing.JRadioButton jRadio_30dias;
    private javax.swing.JRadioButton jRadio_60dias;
    private javax.swing.JRadioButton jRadio_7dias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jT_BI_Painel_Alerta;
    private javax.swing.JTable jT_Pesquisa_Inteligente_tabela;
    private javax.swing.JMenuItem j_venda;
    private javax.swing.JMenuItem jconsulta_produto;
    private javax.swing.JMenuItem jvenda_produto;
    // End of variables declaration//GEN-END:variables

}
